#pragma config(Motor,  port1,           leftOne,       tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port3,           Shooter,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightOne,      tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

#pragma competitionControl(Competition)
#pragma autonomousDuration(0)
#pragma userControlDuration(60)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

void pre_auton()
{
	bStopTasksBetweenModes = true;
}
task autonomous()
{
	AutonomousCodePlaceholderForTesting();
}

task usercontrol()
{
	while (true)
	{
		motor[leftOne] = 127;
		motor[rightOne] = 127;

		wait1Msec(3000);

		motor[leftOne] = 0;
		motor[rightOne] = 0;

		motor[Shooter] = 127;

		wait1Msec(2000);

		motor[Shooter] = 0;
	}
}
